// 日本の国立大学データ（全86校）
export const universitiesData = [
    // 旧帝国大学
    {
        id: 1,
        name: "東京大学",
        nameVariations: [
            "東京大学",
            "とうきょうだいがく",
            "toukyoudaigaku",
            "tokyo daigaku",
            "Tokyo Daigaku",
            "University of Tokyo",
            "Tokyo University",
            "Todai",
            "とうだい",
            "todai",
            "東大",
            "the university of tokyo",
            "tokyo uni",
            "ut",
        ],
        location: "東京都文京区",
        established: 1877,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 2,
        name: "京都大学",
        nameVariations: [
            "京都大学",
            "きょうとだいがく",
            "kyoutodaigaku",
            "kyoto daigaku",
            "Kyoto Daigaku",
            "Kyoto University",
            "Kyodai",
            "きょうだい",
            "kyoudai",
            "京大",
            "kyoto university",
            "kyoto uni",
        ],
        location: "京都府京都市",
        established: 1897,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 3,
        name: "大阪大学",
        nameVariations: [
            "大阪大学",
            "おおさかだいがく",
            "oosakadaigaku",
            "osaka daigaku",
            "Osaka Daigaku",
            "Osaka University",
            "Handai",
            "はんだい",
            "handai",
            "阪大",
            "osaka university",
            "osaka uni",
        ],
        location: "大阪府吹田市",
        established: 1931,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 4,
        name: "東北大学",
        nameVariations: [
            "東北大学",
            "とうほくだいがく",
            "touhokudaigaku",
            "tohoku daigaku",
            "Tohoku Daigaku",
            "Tohoku University",
            "とうほく",
            "tohoku",
            "東北",
            "tohoku university",
            "tohoku uni",
        ],
        location: "宮城県仙台市",
        established: 1907,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 5,
        name: "名古屋大学",
        nameVariations: [
            "名古屋大学",
            "なごやだいがく",
            "nagoyadaigaku",
            "nagoya daigaku",
            "Nagoya Daigaku",
            "Nagoya University",
            "Meidai",
            "めいだい",
            "meidai",
            "名大",
            "nagoya university",
            "nagoya uni",
        ],
        location: "愛知県名古屋市",
        established: 1939,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 6,
        name: "九州大学",
        nameVariations: [
            "九州大学",
            "きゅうしゅうだいがく",
            "kyuushudaigaku",
            "kyushu daigaku",
            "Kyushu Daigaku",
            "Kyushu University",
            "きゅうだい",
            "kyudai",
            "九大",
            "kyushu university",
            "kyushu uni",
        ],
        location: "福岡県福岡市",
        established: 1911,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 7,
        name: "北海道大学",
        nameVariations: [
            "北海道大学",
            "ほっかいどうだいがく",
            "hokkaidoudaigaku",
            "hokkaido daigaku",
            "Hokkaido Daigaku",
            "Hokkaido University",
            "ほくだい",
            "hokudai",
            "北大",
            "hokkaido university",
            "hokkaido uni",
        ],
        location: "北海道札幌市",
        established: 1918,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },

    // 総合大学
    {
        id: 8,
        name: "筑波大学",
        nameVariations: [
            "筑波大学",
            "つくばだいがく",
            "tsukubadaigaku",
            "tsukuba daigaku",
            "Tsukuba Daigaku",
            "University of Tsukuba",
            "Tsukuba University",
            "つくば",
            "tsukuba",
            "tsukuba university",
        ],
        location: "茨城県つくば市",
        established: 1973,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 9,
        name: "広島大学",
        nameVariations: [
            "広島大学",
            "ひろしまだいがく",
            "hiroshimadaigaku",
            "hiroshima daigaku",
            "Hiroshima Daigaku",
            "Hiroshima University",
            "ひろしま",
            "hiroshima",
            "hiroshima university",
        ],
        location: "広島県東広島市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 10,
        name: "神戸大学",
        nameVariations: [
            "神戸大学",
            "こうべだいがく",
            "koubedaigaku",
            "kobe daigaku",
            "Kobe Daigaku",
            "Kobe University",
            "こうべ",
            "kobe",
            "kobe university",
        ],
        location: "兵庫県神戸市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 11,
        name: "千葉大学",
        nameVariations: [
            "千葉大学",
            "ちばだいがく",
            "chibadaigaku",
            "chiba daigaku",
            "Chiba Daigaku",
            "Chiba University",
            "ちば",
            "chiba",
            "chiba university",
        ],
        location: "千葉県千葉市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 12,
        name: "金沢大学",
        nameVariations: [
            "金沢大学",
            "かなざわだいがく",
            "kanazawadaigaku",
            "kanazawa daigaku",
            "Kanazawa Daigaku",
            "Kanazawa University",
            "かなざわ",
            "kanazawa",
            "kanazawa university",
        ],
        location: "石川県金沢市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 13,
        name: "岡山大学",
        nameVariations: [
            "岡山大学",
            "おかやまだいがく",
            "okayamadaigaku",
            "okayama daigaku",
            "Okayama Daigaku",
            "Okayama University",
            "おか  �ま",
            "okayama",
            "okayama university",
        ],
        location: "岡山県岡 ��市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 14,
        name: "熊本大学",
        nameVariations: [
            "熊本大学",
            "くまもとだいがく",
            "kumamotodaigaku",
            "kumamoto daigaku",
            "Kumamoto Daigaku",
            "Kumamoto University",
            "くまもと",
            "kumamoto",
            "kumamoto university",
        ],
        location: "熊本県熊本市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 15,
        name: "新潟大学",
        nameVariations: [
            "新潟大学",
            "にいがただいがく",
            "niigatadaigaku",
            "niigata daigaku",
            "Niigata Daigaku",
            "Niigata University",
            "にいがた",
            "niigata",
            "niigata university",
        ],
        location: "新潟県新潟市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 16,
        name: "信州大学",
        nameVariations: [
            "信州大学",
            "しんしゅうだいがく",
            "shinshudaigaku",
            "shinshu daigaku",
            "Shinshu Daigaku",
            "Shinshu University",
            "しんしゅう",
            "shinshu",
            "shinshu university",
        ],
        location: "長野県松本市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 17,
        name: "静岡大学",
        nameVariations: [
            "静岡大学",
            "しずおかだいがく",
            "shizuokadaigaku",
            "shizuoka daigaku",
            "Shizuoka Daigaku",
            "Shizuoka University",
            "しずおか",
            "shizuoka",
            "shizuoka university",
        ],
        location: "静岡県静岡市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 18,
        name: "群馬大学",
        nameVariations: [
            "群馬大学",
            "ぐんまだいがく",
            "gunmadaigaku",
            "gunma daigaku",
            "Gunma Daigaku",
            "Gunma University",
            "ぐんま",
            "gunma",
            "gunma university",
        ],
        location: "群馬県前橋市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 19,
        name: "山口大学",
        nameVariations: [
            "山口大学",
            "やまぐちだいがく",
            "yamaguchidaigaku",
            "yamaguchi daigaku",
            "Yamaguchi Daigaku",
            "Yamaguchi University",
            "やまぐち",
            "yamaguchi",
            "yamaguchi university",
        ],
        location: "山口県山口市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 20,
        name: "鹿児島大学",
        nameVariations: [
            "鹿児島大学",
            "かごしまだいがく",
            "kagoshimadaigaku",
            "kagoshima daigaku",
            "Kagoshima Daigaku",
            "Kagoshima University",
            "かごしま",
            "kagoshima",
            "kagoshima university",
        ],
        location: "鹿児島県鹿児島市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },

    // 地方国立大学
    {
        id: 21,
        name: "弘前大学",
        nameVariations: [
            "弘前大学",
            "ひろさきだいがく",
            "hirosakidaigaku",
            "hirosaki daigaku",
            "Hirosaki Daigaku",
            "Hirosaki University",
            "ひろさき",
            "hirosaki",
            "hirosaki university",
        ],
        location: "青森県弘前市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 22,
        name: "岩手大学",
        nameVariations: [
            "岩手大学",
            "いわてだいがく",
            "iwatedaigaku",
            "iwate daigaku",
            "Iwate Daigaku",
            "Iwate University",
            "いわて",
            "iwate",
            "iwate university",
        ],
        location: "岩手県盛岡市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 23,
        name: "秋田大学",
        nameVariations: [
            "秋田大学",
            "あきただいがく",
            "akitadaigaku",
            "akita daigaku",
            "Akita Daigaku",
            "Akita University",
            "あきた",
            "akita",
            "akita university",
        ],
        location: "秋田県秋田市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 24,
        name: "山形大学",
        nameVariations: [
            "山形大学",
            "やまがただいがく",
            "yamagatadaigaku",
            "yamagata daigaku",
            "Yamagata Daigaku",
            "Yamagata University",
            "やまがた",
            "yamagata",
            "yamagata university",
        ],
        location: "山形県山形市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 25,
        name: "福島大学",
        nameVariations: [
            "福島大学",
            "ふくしまだいがく",
            "fukushimadaigaku",
            "fukushima daigaku",
            "Fukushima Daigaku",
            "Fukushima University",
            "ふくしま",
            "fukushima",
            "fukushima university",
        ],
        location: "福島県福島市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 26,
        name: "茨城大学",
        nameVariations: [
            "茨城大学",
            "いばらきだいがく",
            "いばらぎだいがく",
            "ibarakidaigaku",
            "ibaraki daigaku",
            "Ibaraki Daigaku",
            "Ibaraki University",
            "いばらき",
            "いばらぎ",
            "ibaraki",
            "ibaraki university",
        ],
        location: "茨城県水戸市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 27,
        name: "宇都宮大学",
        nameVariations: [
            "宇都宮大学",
            "うつのみやだいがく",
            "utsunomiyadaigaku",
            "utsunomiya daigaku",
            "Utsunomiya Daigaku",
            "Utsunomiya University",
            "うつのみや",
            "utsunomiya",
            "utsunomiya university",
        ],
        location: "栃木県宇都宮市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 28,
        name: "埼玉大学",
        nameVariations: [
            "埼玉大学",
            "さいたまだいがく",
            "saitamadaigaku",
            "saitama daigaku",
            "Saitama Daigaku",
            "Saitama University",
            "さいたま",
            "saitama",
            "saitama university",
        ],
        location: "埼玉県さいたま市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 29,
        name: "横浜国立大学",
        nameVariations: [
            "横浜国立大学",
            "よこはまこくりつだいがく",
            "yokohamakokuritsudaigaku",
            "yokohama kokuritsu daigaku",
            "Yokohama Kokuritsu Daigaku",
            "Yokohama National University",
            "よこはまこくりつ",
            "yokohama",
            "yokohama national university",
            "YNU",
        ],
        location: "神奈川県横浜市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 30,
        name: "山梨大学",
        nameVariations: [
            "山梨大学",
            "やまなしだいがく",
            "yamanashidaigaku",
            "yamanashi daigaku",
            "Yamanashi Daigaku",
            "Yamanashi University",
            "やまなし",
            "yamanashi",
            "yamanashi university",
        ],
        location: "山梨県甲府市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 31,
        name: "富山大学",
        nameVariations: [
            "富山大学",
            "とやまだいがく",
            "toyamadaigaku",
            "toyama daigaku",
            "Toyama Daigaku",
            "Toyama University",
            "とやま",
            "toyama",
            "toyama university",
        ],
        location: "富山県富山市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 32,
        name: "福井大学",
        nameVariations: [
            "福井大学",
            "ふくいだいがく",
            "fukuidaigaku",
            "fukui daigaku",
            "Fukui Daigaku",
            "Fukui University",
            "ふくい",
            "fukui",
            "fukui university",
        ],
        location: "福井県福井市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 33,
        name: "岐阜大学",
        nameVariations: [
            "岐阜大学",
            "ぎふだいがく",
            "gifudaigaku",
            "gifu daigaku",
            "Gifu Daigaku",
            "Gifu University",
            "ぎふ",
            "gifu",
            "gifu university",
        ],
        location: "岐阜県岐阜市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 34,
        name: "三重大学",
        nameVariations: [
            "三重大学",
            "みえだいがく",
            "miedaigaku",
            "mie daigaku",
            "Mie Daigaku",
            "Mie University",
            "みえ",
            "mie",
            "mie university",
        ],
        location: "三重県津市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 35,
        name: "滋賀大学",
        nameVariations: [
            "滋賀大学",
            "しがだいがく",
            "shigadaigaku",
            "shiga daigaku",
            "Shiga Daigaku",
            "Shiga University",
            "しが",
            "shiga",
            "shiga university",
        ],
        location: "滋賀県大津市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 36,
        name: "奈良国立大学機構",
        location: "奈良県奈良市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 37,
        name: "和歌山大学",
        nameVariations: [
            "和歌山大学",
            "わかやまだいがく",
            "wakayamadaigaku",
            "wakayama daigaku",
            "Wakayama Daigaku",
            "Wakayama University",
            "わかやま",
            "wakayama",
            "wakayama university",
        ],
        location: "和歌山県和歌山市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 38,
        name: "鳥取大学",
        nameVariations: [
            "鳥取大学",
            "とっとりだいがく",
            "tottoridaigaku",
            "tottori daigaku",
            "Tottori Daigaku",
            "Tottori University",
            "とっとり",
            "tottori",
            "tottori university",
        ],
        location: "鳥取県鳥取市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 39,
        name: "島根大学",
        nameVariations: [
            "島根大学",
            "しまねだいがく",
            "shimanedaigaku",
            "shimane daigaku",
            "Shimane Daigaku",
            "Shimane University",
            "しまね",
            "shimane",
            "shimane university",
        ],
        location: "島根県松江市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 40,
        name: "徳島大学",
        nameVariations: [
            "徳島大学",
            "とくしまだいがく",
            "tokushimadaigaku",
            "tokushima daigaku",
            "Tokushima Daigaku",
            "Tokushima University",
            "とくしま",
            "tokushima",
            "tokushima university",
        ],
        location: "徳島県徳島市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 41,
        name: "香川大学",
        nameVariations: [
            "香川大学",
            "かがわだいがく",
            "kagawadaigaku",
            "kagawa daigaku",
            "Kagawa Daigaku",
            "Kagawa University",
            "かがわ",
            "kagawa",
            "kagawa university",
        ],
        location: "香川県高松市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 42,
        name: "愛媛大学",
        nameVariations: [
            "愛媛大学",
            "えひめだいがく",
            "ehimedaigaku",
            "ehime daigaku",
            "Ehime Daigaku",
            "Ehime University",
            "えひめ",
            "ehime",
            "ehime university",
        ],
        location: "愛媛県松山市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 43,
        name: "高知大学",
        nameVariations: [
            "高知大学",
            "こうちだいがく",
            "kouchidaigaku",
            "kochi daigaku",
            "Kochi Daigaku",
            "Kochi University",
            "こうち",
            "kochi",
            "kochi university",
        ],
        location: "高知県高知市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 44,
        name: "佐賀大学",
        nameVariations: [
            "佐賀大学",
            "さがだいがく",
            "sagadaigaku",
            "saga daigaku",
            "Saga Daigaku",
            "Saga University",
            "さが",
            "saga",
            "saga university",
        ],
        location: "佐賀県佐賀市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 45,
        name: "長崎大学",
        nameVariations: [
            "長崎大学",
            "ながさきだいがく",
            "nagasakidaigaku",
            "nagasaki daigaku",
            "Nagasaki Daigaku",
            "Nagasaki University",
            "ながさき",
            "nagasaki",
            "nagasaki university",
        ],
        location: "長崎県長崎市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 46,
        name: "大分大学",
        nameVariations: [
            "大分大学",
            "おおいただいがく",
            "oitadaigaku",
            "oita daigaku",
            "Oita Daigaku",
            "Oita University",
            "おおいた",
            "oita",
            "oita university",
        ],
        location: "大分県大分市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 47,
        name: "宮崎大学",
        nameVariations: [
            "宮崎大学",
            "みやざきだいがく",
            "miyazakidaigaku",
            "miyazaki daigaku",
            "Miyazaki Daigaku",
            "Miyazaki University",
            "みやざき",
            "miyazaki",
            "miyazaki university",
        ],
        location: "宮崎県宮崎市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 48,
        name: "琉球大学",
        nameVariations: [
            "琉球大学",
            "りゅうきゅうだいがく",
            "ryuukyuudaigaku",
            "ryukyu daigaku",
            "Ryukyu Daigaku",
            "University of the Ryukyus",
            "りゅうきゅう",
            "ryukyu",
            "ryukyus",
            "university of the ryukyus",
        ],
        location: "沖縄県西原町",
        established: 1950,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },

    // 単科大学・特色ある大学
    {
        id: 49,
        name: "東京工業大学",
        nameVariations: [
            "東京工業大学",
            "とうきょうこうぎょうだいがく",
            "Tokyo Kogyo Daigaku",
            "Tokyo Institute of Technology",
            "Tokyo Tech",
            "Titech",
            "とうこうだい",
            "東工大",
        ],
        location: "東京都目黒区",
        established: 1929,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 50,
        name: "一橋大学",
        nameVariations: [
            "一橋大学",
            "ひとつばしだいがく",
            "Hitotsubashi Daigaku",
            "Hitotsubashi University",
            "ひとつばし",
            "一橋",
        ],
        location: "東京都国立市",
        established: 1920,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 51,
        name: "東京外国語大学",
        nameVariations: [
            "東京外国語大学",
            "とうきょうがいこくごだいがく",
            "toukyougaikokugodaigaku",
            "tokyo gaikokugo daigaku",
            "Tokyo Gaikokugo Daigaku",
            "Tokyo University of Foreign Studies",
            "とうきょうがいこくご",
            "がいだい",
            "gaidai",
            "tufs",
            "tokyo university of foreign studies",
        ],
        location: "東京都府中市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 52,
        name: "東京農工大学",
        nameVariations: [
            "東京農工大学",
            "とうきょうのうこうだいがく",
            "toukyounokoudaigaku",
            "tokyo nouko daigaku",
            "Tokyo Nouko Daigaku",
            "Tokyo University of Agriculture and Technology",
            "とうきょうのうこう",
            "のうこうだい",
            "noko",
            "tuat",
            "tokyo university of agriculture and technology",
        ],
        location: "東京都府中市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 53,
        name: "東京海洋大学",
        nameVariations: [
            "東京海洋大学",
            "とうきょうかいようだいがく",
            "toukyoukaiyoudaigaku",
            "tokyo kaiyo daigaku",
            "Tokyo Kaiyo Daigaku",
            "Tokyo University of Marine Science and Technology",
            "とうきょうかいよう",
            "かいようa��い",
            "kaiyo",
            "tumsat",
            "tokyo university of marine science and technology",
        ],
        location: "東京都港区",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 54,
        name: "お茶の水女子大学",
        nameVariations: [
            "お茶の水女子大学",
            "おちゃのみずじょしだいがく",
            "ochanomizujoshidaigaku",
            "ochanomizu joshi daigaku",
            "Ochanomizu Joshi Daigaku",
            "Ochanomizu University",
            "おちゃのみず",
            "ochanomizu",
            "ochanomizu university",
        ],
        location: "東京都文京区",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 55,
        name: "電気通信大学",
        nameVariations: [
            "電気通信大学",
            "でんきつうしんだいがく",
            "denkitsuushindaigaku",
            "denki tsushin daigaku",
            "Denki Tsushin Daigaku",
            "University of Electro-Communications",
            "でんきつうしん",
            "でんつう",
            "dentsu",
            "uec",
            "university of electro-communications",
        ],
        location: "東京都調布市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 56,
        name: "東京学芸大学",
        nameVariations: [
            "東京学芸大学",
            "とうきょうがくげいだいがく",
            "toukyougakugeidaigaku",
            "tokyo gakugei daigaku",
            "Tokyo Gakugei Daigaku",
            "Tokyo Gakugei University",
            "とうきょうがくげい",
            "がくげい",
            "gakugei",
            "tokyo gakugei university",
        ],
        location: "東京都小金井市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 57,
        name: "東京芸術大学",
        nameVariations: [
            "東京芸術大学",
            "とうきょうげいじゅつだいがく",
            "toukyougeijutsudaigaku",
            "tokyo geijutsu daigaku",
            "Tokyo Geijutsu Daigaku",
            "Tokyo University of the Arts",
            "とうきょうげいじゅつ",
            "げいだい",
            "geidai",
            "tokyo university of the arts",
        ],
        location: "東京都台東区",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 58,
        name: "北見工業大学",
        nameVariations: [
            "北見工業大学",
            "きたみこうぎょうだいがく",
            "kitamikougyoudaigaku",
            "kitami kougyou daigaku",
            "Kitami Kougyou Daigaku",
            "Kitami Institute of Technology",
            "きたみこうぎょう",
            "きたみ",
            "kitami",
            "北見工業",
            "北見",
            "kitami institute of technology",
            "kitami tech",
        ],
        location: "北海道北見市",
        established: 1960,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 59,
        name: "室蘭工業大学",
        nameVariations: [
            "室蘭工業大学",
            "むろらんこうぎょうだいがく",
            "muroran kougyou daigaku",
            "muroran kougyou daigaku",
            "Muroran Kougyou Daigaku",
            "Muroran Institute of Technology",
            "むろらんこうぎょう",
            "むろらん",
            "muroran",
            "室蘭工業",
            "室蘭",
            "muroran institute of technology",
            "muroran tech",
        ],
        location: "北海道室蘭市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 60,
        name: "小樽商科大学",
        nameVariations: [
            "小樽商科大学",
            "おたるしょうかだいがく",
            "otarushokadaigaku",
            "otaru shoka daigaku",
            "Otaru Shoka Daigaku",
            "Otaru University of Commerce",
            "おたるしょうか",
            "おたる",
            "otaru",
            "小樽商科",
            "小樽",
            "otaru university of commerce",
            "otaru commerce",
        ],
        location: "北海道小樽市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 61,
        name: "帯広畜産大学",
        nameVariations: [
            "帯広畜産大学",
            "おびひろちくさんだいがく",
            "obihirochikusandaigaku",
            "obihiro chikusan daigaku",
            "Obihiro Chikusan Daigaku",
            "Obihiro University of Agriculture and Veterinary Medicine",
            "おびひろちくさん",
            "おびひろ",
            "obihiro",
            "帯広畜産",
            "帯広",
            "obihiro university of agriculture and veterinary medicine",
            "obihiro agriculture",
        ],
        location: "北海道帯広市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 62,
        name: "旭川医科大学",
        nameVariations: [
            "旭川医科大学",
            "あさひかわいかだいがく",
            "asahikawaikadaigaku",
            "asahikawa ika daigaku",
            "Asahikawa Ika Daigaku",
            "Asahikawa Medical University",
            "あさひかわいか",
            "あさひかわ",
            "asahikawa",
            "旭川医科",
            "旭川",
            "asahikawa medical university",
            "asahikawa medical",
        ],
        location: "北海道旭川市",
        established: 1973,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 63,
        name: "北海道教育大学",
        nameVariations: [
            "北海道教育大学",
            "ほっかいどうきょういくだいがく",
            "hokkaidoukyouikudaigaku",
            "hokkaido kyouiku daigaku",
            "Hokkaido Kyouiku Daigaku",
            "Hokkaido University of Education",
            "ほっかいどうきょういく",
            "ほっかいどう",
            "hokkaido",
            "北海道教育",
            "北海道",
            "hokkaido university of education",
            "hokkaido education",
        ],
        location: "北海道札幌市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 64,
        name: "奈良教育大学",
        nameVariations: [
            "is�良教育大学",
            "ならきょういくだいがく",
            "narakyouikudaigaku",
            "nara kyouiku daigaku",
            "Nara Kyouiku Daigaku",
            "Nara University of Education",
            "ならきょういく",
            "なら",
            "nara",
            "奈良教育",
            "奈良",
            "nara university of education",
            "nara education",
        ],
        location: "奈良県奈良市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 65,
        name: "京都教育大学",
        nameVariations: [
            "京都教育大学",
            "きょうときょういくだいがく",
            "kyoutokyouikudaigaku",
            "kyoto kyouiku daigaku",
            "Kyoto Kyouiku Daigaku",
            "Kyoto University of Education",
            "きょうときょういく",
            "きょうと",
            "kyoto",
            "京都教育",
            "京都",
            "kyoto university of education",
            "kyoto education",
        ],
        location: "京都府京都市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 66,
        name: "大阪教育大学",
        nameVariations: [
            "大阪教育大学",
            "おおさかきょういくだいがく",
            "oosakakyouikudaigaku",
            "osaka kyouiku daigaku",
            "Osaka Kyouiku Daigaku",
            "Osaka Kyoiku University",
            "おおさかきょういく",
            "おおさか",
            "osaka",
            "大阪教育",
            "大阪",
            "osaka kyoiku university",
            "osaka education",
        ],
        location: "大阪府柏原市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 67,
        name: "兵庫教育大学",
        nameVariations: [
            "兵庫教育大学",
            "ひょうごきょういくだいがく",
            "hyougokyouikudaigaku",
            "hyogo kyouiku daigaku",
            "Hyogo Kyouiku Daigaku",
            "Hyogo University of Teacher Education",
            "ひょうごきょういく",
            "ひょうご",
            "hyogo",
            "兵庫教育",
            "兵庫",
            "hyogo university of teacher education",
            "hyogo education",
        ],
        location: "兵庫県加東市",
        established: 1978,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 68,
        name: "京都工芸繊維大学",
        nameVariations: [
            "京都工芸繊維大学",
            "きょうとこうげいせんいだいがく",
            "kyoutokougeisendaigaku",
            "kyoto kougei sen'i daigaku",
            "Kyoto Kougei Sen'i Daigaku",
            "Kyoto Institute of Technology",
            "きょうとこうげいせんい",
            "きょうと",
            "kyoto",
            "京都工芸繊維",
            "京都工繊",
            "kyoto institute of technology",
            "kyoto tech",
        ],
        location: "京都府京都市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 69,
        name: "奈良先端科学技術大学院大学",
        nameVariations: [
            "奈良先端科学技術大学院大学",
            "ならせんたんかがくぎじゅつだいがくいんだいがく",
            "narasentankagakugijutsudaigakuindaigaku",
            "nara sentan kagaku gijutsu daigakuin daigaku",
            "Nara Sentan Kagaku Gijutsu Daigakuin Daigaku",
            "Nara Institute of Science and Technology",
            "ならせんたん",
            "なら",
            "nara",
            "奈良先端",
            "NAIST",
            "nara institute of science and technology",
            "naist",
        ],
        location: "奈良県生駒市",
        established: 1991,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 70,
        name: "九州工業大学",
        nameVariations: [
            "九州工業大学",
            "きゅうしゅうこうぎょうだいがく",
            "kyuushukougyoudaigaku",
            "kyushu kougyou daigaku",
            "Kyushu Kougyou Daigaku",
            "Kyushu Institute of Technology",
            "きゅうしゅうこうぎょう",
            "きゅうしゅう",
            "kyushu",
            "九州工業",
            "九工大",
            "kyushu institute of technology",
            "kyutech",
        ],
        location: "福岡県北九州市",
        established: 1949,
        type: "国立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },

    // 主要私立大学
    {
        id: 71,
        name: "早稲田大学",
        nameVariations: [
            "早稲田大学",
            "わせだだいがく",
            "wasedadaigaku",
            "waseda daigaku",
            "Waseda Daigaku",
            "Waseda University",
            "Waseda",
            "わせだ",
            "waseda",
            "早稲田",
            "waseda university",
            "waseda uni",
        ],
        location: "東京都新宿区",
        established: 1882,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 72,
        name: "慶應義塾大学",
        nameVariations: [
            "慶應義塾大学",
            "けいおうぎじゅくだいがく",
            "keiougijukudaigaku",
            "keio gijuku daigaku",
            "Keio Gijuku Daigaku",
            "Keio University",
            "Keio",
            "けいお",
            "keio",
            "慶應",
            "慶応",
            "keio university",
            "keio uni",
        ],
        location: "東京都港区",
        established: 1858,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 73,
        name: "上智大学",
        nameVariations: [
            "上智大学",
            "じょうちだいがく",
            "jouchidaigaku",
            "jochi daigaku",
            "Jochi Daigaku",
            "Sophia University",
            "Sophia",
            "じょうち",
            "jochi",
            "上智",
            "sophia university",
            "sophia",
        ],
        location: "東京都千代田区",
        established: 1913,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 74,
        name: "立教大学",
        nameVariations: [
            "立教大学",
            "りっきょうだいがく",
            "rikkyoudaigaku",
            "rikkyo daigaku",
            "Rikkyo Daigaku",
            "Rikkyo University",
            "りっきょう",
            "rikkyo",
            "立教",
            "rikkyo university",
        ],
        location: "東京都豊島区",
        established: 1874,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 75,
        name: "明治大学",
        nameVariations: [
            "明治大学",
            "めいじだいがく",
            "meijidaigaku",
            "meiji daigaku",
            "Meiji Daigaku",
            "Meiji University",
            "めいじ",
            "meiji",
            "明治",
            "meiji university",
        ],
        location: "東京都千代田区",
        established: 1881,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 76,
        name: "青山学院大学",
        nameVariations: [
            "青山学院大学",
            "あおやまがくいんだいがく",
            "aoyamagakuindaigaku",
            "aoyama gakuin daigaku",
            "Aoyama Gakuin Daigaku",
            "Aoyama Gakuin University",
            "あおやまがくいん",
            "aoyamagakuin",
            "aoyama gakuin",
            "aoyama gakuin university",
        ],
        location: "東京都渋谷区",
        established: 1874,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 77,
        name: "中央大学",
        nameVariations: [
            "中央大学",
            "ちゅうおうだいがく",
            "chuuoudaigaku",
            "chuo daigaku",
            "Chuo Daigaku",
            "Chuo University",
            "ちゅうおう",
            "chuo",
            "中央",
            "chuo university",
        ],
        location: "東京都八王子市",
        established: 1885,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 78,
        name: "法政大学",
        nameVariations: [
            "法政大学",
            "ほうせいだいがく",
            "houseidaigaku",
            "hosei daigaku",
            "Hosei Daigaku",
            "Hosei University",
            "ほうせい",
            "hosei",
            "hosei university",
        ],
        location: "東京都千代田区",
        established: 1880,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 79,
        name: "学習院大学",
        nameVariations: [
            "学習院大学",
            "がくしゅういんだいがく",
            "gakushuindaigaku",
            "gakushuin daigaku",
            "Gakushuin Daigaku",
            "Gakushuin University",
            "がくしゅういん",
            "gakushuin",
            "gakushuin university",
        ],
        location: "東京都豊島区",
        established: 1949,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 80,
        name: "成蹊大学",
        nameVariations: [
            "成蹊大学",
            "せいけいだいがく",
            "seikeidaigaku",
            "seikei daigaku",
            "Seikei Daigaku",
            "Seikei University",
            "せいけい",
            "seikei",
            "seikei university",
        ],
        location: "東京都武蔵野市",
        established: 1949,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 81,
        name: "関西大学",
        nameVariations: [
            "関西大学",
            "かんさいだいがく",
            "kansaidaigaku",
            "kansai daigaku",
            "Kansai Daigaku",
            "Kansai University",
            "かんさい",
            "kansai",
            "kansai university",
        ],
        location: "大阪府吹田市",
        established: 1886,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 82,
        name: "関西学院大学",
        nameVariations: [
            "関西学院大学",
            "かんせいがくいんだいがく",
            "kanseigakuindaigaku",
            "kansei gakuin daigaku",
            "Kansei Gakuin Daigaku",
            "Kwansei Gakuin University",
            "かんせいがくいん",
            "kanseigakuin",
            "kwansei gakuin university",
            "KGU",
        ],
        location: "兵庫県西宮市",
        established: 1889,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 83,
        name: "同志社大学",
        nameVariations: [
            "同志社大学",
            "どうししゃだいがく",
            "doushishadaigaku",
            "doshisha daigaku",
            "Doshisha Daigaku",
            "Doshisha University",
            "どうししゃ",
            "doshisha",
            "doshisha university",
        ],
        location: "京都府京都市",
        established: 1875,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 84,
        name: "立命館大学",
        nameVariations: [
            "立命館大学",
            "りつめいかんだいがく",
            "ritsumeikandaigaku",
            "ritsumeikan daigaku",
            "Ritsumeikan Daigaku",
            "Ritsumeikan University",
            "りつめいかん",
            "ritsumeikan",
            "ritsumeikan university",
        ],
        location: "京都府京都市",
        established: 1900,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 85,
        name: "近畿大学",
        nameVariations: [
            "近畿大学",
            "きんきだいがく",
            "kinkidaigaku",
            "kinki daigaku",
            "Kinki Daigaku",
            "Kindai University",
            "きんき",
            "kinki",
            "kindai",
            "kindai university",
        ],
        location: "大阪府東大阪市",
        established: 1925,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 86,
        name: "龍谷大学",
        nameVariations: [
            "龍谷大学",
            "りゅうこくだいがく",
            "ryuukokudaigaku",
            "ryukoku daigaku",
            "Ryukoku Daigaku",
            "Ryukoku University",
            "りゅうこく",
            "ryukoku",
            "ryukoku university",
        ],
        location: "京都府京都市",
        established: 1639,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 87,
        name: "専修大学",
        nameVariations: [
            "専修大学",
            "せんしゅうだいがく",
            "senshudaigaku",
            "senshu daigaku",
            "Senshu Daigaku",
            "Senshu University",
            "せんしゅう",
            "senshu",
            "senshu university",
        ],
        location: "東R��都千代田区",
        established: 1880,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 88,
        name: "東洋大学",
        nameVariations: [
            "東洋大学",
            "とうようだいがく",
            "touyoudaigaku",
            "toyo daigaku",
            "Toyo Daigaku",
            "Toyo University",
            "とうよう",
            "toyo",
            "東洋",
            "toyo university",
        ],
        location: "東京都文京区",
        established: 1887,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 89,
        name: "駒澤大学",
        nameVariations: [
            "駒澤大学",
            "駒沢大学",
            "こまざわだいがく",
            "komazawadaigaku",
            "komazawa daigaku",
            "Komazawa Daigaku",
            "Komazawa University",
            "こまざわ",
            "komazawa",
            "駒澤",
            "駒沢",
            "komazawa university",
        ],
        location: "東京都世田谷区",
        established: 1592,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 90,
        name: "日本大学",
        nameVariations: [
            "日本大学",
            "にほんだいがく",
            "にっぽんだいがく",
            "nihondaigaku",
            "nippondaigaku",
            "nihon daigaku",
            "nippon daigaku",
            "Nihon Daigaku",
            "Nippon University",
            "にほん",
            "にっぽん",
            "nihon",
            "nippon",
            "日本",
            "nihon university",
            "nichidai",
            "にちだい",
        ],
        location: "東京都千代田区",
        established: 1889,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },

    // 産近甲龍（追加分）
    {
        id: 91,
        name: "京都産業大学",
        nameVariations: [
            "京都産業大学",
            "きょうとさんぎょうだいがく",
            "kyoutosangyoudaigaku",
            "kyoto sangyo daigaku",
            "Kyoto Sangyo Daigaku",
            "Kyoto Sangyo University",
            "きょうとさんぎょう",
            "kyotosangyo",
            "京都産業",
            "京産大",
            "kyoto sangyo university",
            "kyoto sangyo",
        ],
        location: "京都府京都市",
        established: 1965,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 92,
        name: "甲南大学",
        nameVariations: [
            "甲南大学",
            "こうなんだいがく",
            "kounandaigaku",
            "konan daigaku",
            "Konan Daigaku",
            "Konan University",
            "こうなん",
            "konan",
            "甲南",
            "konan university",
        ],
        location: "兵庫県神戸市",
        established: 1919,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },

    // 成成明学獨國武
    {
        id: 93,
        name: "成蹊大学",
        nameVariations: [
            "成蹊大学",
            "せいけいだいがく",
            "seikeidaigaku",
            "seikei daigaku",
            "Seikei Daigaku",
            "Seikei University",
            "せいけい",
            "seikei",
            "seikei university",
        ],
        location: "東京都武蔵野市",
        established: 1949,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 94,
        name: "成城大学",
        nameVariations: [
            "成城大学",
            "せいじょうだいがく",
            "seijoudaigaku",
            "seijo daigaku",
            "Seijo Daigaku",
            "Seijo University",
            "せいじょう",
            "seijo",
            "seijo university",
        ],
        location: "東京都世田谷区",
        established: 1950,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 95,
        name: "明治学院大学",
        nameVariations: [
            "明治学院大学",
            "めいじがくいんだいがく",
            "meijigakuindaigaku",
            "meiji gakuin daigaku",
            "Meiji Gakuin Daigaku",
            "Meiji Gakuin University",
            "めいじがくいん",
            "meijigakuin",
            "meiji gakuin",
            "meiji gakuin university",
        ],
        location: "東京都港区",
        established: 1863,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 96,
        name: "獨協大学",
        nameVariations: [
            "獨協大学",
            "独協大学",
            "どっきょうだいがく",
            "dokkyoudaigaku",
            "dokkyo daigaku",
            "Dokkyo Daigaku",
            "Dokkyo University",
            "どっきょう",
            "dokkyo",
            "dokkyo university",
        ],
        location: "埼玉県草加市",
        established: 1881,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 97,
        name: "國學院大學",
        nameVariations: [
            "國學院大學",
            "国学院大学",
            "こくがくいんだいがく",
            "kokugakuindaigaku",
            "kokugakuin daigaku",
            "Kokugakuin Daigaku",
            "Kokugakuin University",
            "こくがくいん",
            "kokugakuin",
            "kokugakuin university",
        ],
        location: "東京都渋谷区",
        established: 1882,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
    {
        id: 98,
        name: "武蔵大学",
        nameVariations: [
            "武蔵大学",
            "むさしだいがく",
            "musashidaigaku",
            "musashi daigaku",
            "Musashi Daigaku",
            "Musashi University",
            "むさし",
            "musashi",
            "musashi university",
        ],
        location: "東京都練馬区",
        established: 1922,
        type: "私立",
        overallRating: 0,
        academicRating: 0,
        facilityRating: 0,
        employmentRating: 0,
        reviewCount: 0,
    },
];

// 大学レビューデータ
export const universityReviewsData = [];

// 教授データベース（国立大学の代表的な教授）
export const professorsData = [
    // 東京大学
    {
        id: 1,
        name: "大山　雄己",
        universityId: 1,
        university: "東京大学",
        department: "工学部",
        overallRating: 0,
        difficulty: 0,
        strictness: 0,
        reviewCount: 0,
    },
];

// レビューデータ
export const reviewsData = [];
